name: KBC Tests
description: Runs KBC platform integration tests if configured

inputs:
  app_id:
    description: Component ID (e.g. kds-team.ex-airtable)
    required: true
  image_tag:
    description: Docker image tag to test
    required: true
  kbc_test_configs:
    description: Space-separated list of KBC test config IDs
    required: false
    default: ""
  kbc_storage_token:
    description: KBC Storage API token
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Run KBC test jobs
      if: inputs.kbc_test_configs != '' && inputs.kbc_storage_token != ''
      uses: keboola/action-run-configs-parallel@master
      with:
        token: ${{ inputs.kbc_storage_token }}
        componentId: ${{ inputs.app_id }}
        tag: ${{ inputs.image_tag }}
        configs: ${{ inputs.kbc_test_configs }}
